LLAMA_CLOUD_API_KEY: 'ВВЕДИТЕ КЛЮЧ'
HHFAPI: 'ВВЕДИТЕ КЛЮЧ'
PineconeAPI: 'ВВЕДИТЕ КЛЮЧ'

QAGenerator_model_repo: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
chunk_size: 200
reader_model_repo: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
tokenizer: 'thenlper/gte-small'
rerank: True
eval_chat_model: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
